import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:jambar_pay_mobile/l10n/app_localizations.dart';

void main() {
  test('French and English expose every application message', () async {
    for (final locale in AppLocalizations.supportedLocales) {
      final loc = AppLocalizations(locale);
      final messages = <String>[
        loc.appTitle,
        loc.chooseLanguage,
        loc.french,
        loc.english,
        loc.languageChangedFrench,
        loc.languageChangedEnglish,
        loc.contactSupport,
        loc.email,
        loc.phone,
        loc.ok,
        loc.secretCodeChanged,
        loc.logout,
        loc.logoutConfirm,
        loc.cancel,
        loc.logoutButton,
        loc.darkMode,
        loc.lightMode,
        loc.changeSecretCode,
        loc.back,
        loc.home,
        loc.history,
        loc.restaurants,
        loc.profile,
        loc.accountPage,
        loc.enterAmountToPay,
        loc.availableBalanceTitle,
        loc.availableBalance('1 000 Fcfa'),
        loc.amount,
        loc.pay,
        loc.invalidAmount,
        loc.insufficientBalance,
        loc.paymentSuccess,
        loc.paymentSuccessBody('1 000 Fcfa', 'Le FOOD'),
        loc.finish,
        loc.retry,
        loc.noTransactionsAvailable,
        loc.noRestaurantsAvailable,
        loc.noTransactionsMatchSearch,
        loc.filterAll,
        loc.filterToday,
        loc.filterThisWeek,
        loc.filterThisMonth,
        loc.searchTransactions,
        loc.statusPending,
        loc.statusValidated,
        loc.statusFailed,
        loc.dateToday,
        loc.dateYesterday,
        loc.recentTransactions,
        loc.viewAll,
        loc.map,
        loc.list,
        loc.restaurantsNearby(1),
        loc.restaurantsNearby(3),
        loc.paymentSuccessMessage('Le FOOD'),
        loc.partnerRestaurant,
        loc.currentSecretCode,
        loc.newSecretCode,
        loc.confirmation,
        loc.enterYourCurrentCode,
        loc.chooseNewSecretCode,
        loc.enterNewSecretCodeAgain,
        loc.setYourNewSecretCode,
        loc.enterCodeAgain,
        loc.codeMismatch,
        loc.current,
        loc.newLabel,
        loc.confirmationShort,
        loc.pinCode,
        loc.enterYourPinCode,
        loc.retryIn('30s'),
        loc.secretCodeResetSuccess,
        loc.forgotPin,
        loc.loginTitle,
        loc.continueLabel,
        loc.enterPhoneNumber,
        loc.phoneNumberLabel,
        loc.resetSecretCode,
        loc.verificationCode,
        loc.verificationCodeShort,
        loc.enterVerificationCode,
        loc.accountForPhone('77 123 45 67'),
        loc.confirmCode,
        loc.scan,
        loc.myQr,
        loc.invalidQrCode,
        loc.cameraUnavailable,
        loc.transactionCount(1),
        loc.transactionCount(2),
        loc.progressiveLoadingActive,
        loc.loadMore,
        loc.searchRestaurant,
        loc.open,
        loc.closed,
        loc.walletUnavailable,
        loc.scanQrCode,
        loc.qrDetected('token'),
        loc.employeeQr,
        loc.activeEmployeeQr,
        loc.readyForScan,
        loc.phoneTooLong,
        loc.invalidPhoneNumber,
        loc.incorrectSecretCode(2, 'attempts'),
        loc.youCanRetryNow,
        loc.validated,
        loc.active,
        loc.todayAt('12h00'),
        loc.yesterdayAt('12h00'),
        loc.dateTime('01/01/2030', '12h00'),
        loc.paymentConfirmed,
        loc.paymentConfirmedBody('Le FOOD'),
        loc.balanceUpdated,
        loc.walletSynced,
        loc.employerTopUp,
        loc.deleteLastDigit,
        loc.pinDigitsEntered(2, 4),
      ];

      expect(messages, everyElement(isNotEmpty));
      expect(messages, everyElement(isNot(contains(RegExp(r'\{\w+\}')))));
    }

    expect(AppLocalizations.delegate.isSupported(const Locale('fr')), isTrue);
    expect(AppLocalizations.delegate.isSupported(const Locale('wo')), isFalse);
    expect(
      await AppLocalizations.delegate.load(const Locale('en')),
      isA<AppLocalizations>(),
    );
    expect(
      AppLocalizations.delegate.shouldReload(AppLocalizations.delegate),
      isFalse,
    );
  });

  test('unsupported locales fall back to English', () {
    final loc = AppLocalizations(const Locale('wo'));
    expect(loc.continueLabel, 'Continue');
  });
}
